- name: Create ROSA-HCP Cluster
  hosts: localhost
  any_errors_fatal: true
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Prepare ansible runner host
      include_tasks: tasks/prepare_ansible_runner.yml
      when: not skip_ansible_runner | bool

    - name: Login OCP
      vars:
        ocp_user: "{{ ocp_user }}"
        ocp_user_password: "{{ ocp_user_password }}"
      include_tasks: tasks/login_ocp.yml

    - set_fact:
        enable: "true"
        component: "cluster-api"

    - name: Enable capi
      include_tasks: tasks/update_enabled_flag.yml

    - set_fact:
        enable: "true"
        component: "cluster-api-provider-aws"

    - name: Enable capa
      include_tasks: tasks/update_enabled_flag.yml

    - name: Create ROSA-HCP Cluster
      import_role:
        name: capa-cluster-create-rosa-hcp
