- name: CAPI assistant
  hosts: localhost
  any_errors_fatal: true
  vars_files:
    - vars/vars.yml
    - vars/user_vars.yml
  vars_prompt:
    - name: selected_action
      prompt: |
       Choose one of the following:
          1 - Verify MCE CAPI/CAPA environment.
          2 - Configure MCE CAPI/CAPA environment for ROSA_HCP cluster creation.
          3 - Check CAPA/CAPA enabled status.
          4 - Enable CAPA/CAPA.
          5 - Enable ClusterManager auto-import (Add the registrationConfiguration section).
          6 - Apply ClusterRoleBinding changes (cluster-manager-registration-capi).
          7 - Create capa-manager-bootstrap-credentials.
          8 - Restart capa-controller-manager deployment.
          9 - Create rosa-creds-secret.
         10 - Show the ROSAControlPlane "ready" status.
         11 - Create the ROSA_HCP cluster or other resource. (oc apply -f <filename>)
         12 - Delete the ROSA_HCP cluster or other resource. (oc delete -f <filename>)
      private: no
  tasks:
    - set_fact:
        ocp_user:  "{{ OCP_HUB_CLUSTER_USER }}"
        ocp_password:  "{{ OCP_HUB_CLUSTER_PASSWORD }}"
        api_url:  "{{ OCP_HUB_API_URL }}"
        mce_namespace: "{{ MCE_NAMESPACE }}"

    - name: Prepare ansible runner host
      include_tasks: tasks/prepare_ansible_runner.yml
      when: not skip_ansible_runner | bool

    - name: Login OCP
      include_tasks: tasks/login_ocp.yml

    - name: Get capi/capa resources
      include_tasks: tasks/get_capi_resources.yml
      when: selected_action == "1"

    - name: Get capi/capa status
      include_tasks: tasks/get_capi_capa_status.yml
      when: selected_action == "3"

    - name: Enable CAPI and CAPA
      include_tasks: tasks/enable_capi_capa.yml
      when: selected_action == "4"

    - name: Set ClusterManager registrationConfiguration to enable auto-import.
      include_tasks: tasks/set_registration_configuration.yml
      when: selected_action == "5"

    - name: Create cluster-manager-registration-capi ClusterRoleBinding.
      include_tasks: tasks/set_cluster_role_binding.yml
      when: selected_action == "6"

    - name: Create capa-manager-bootstrap-credentials with AWS Credentials
      include_tasks: tasks/create_capa_manager_bootstrap_credentials.yml
      when: selected_action == "7"

    - name: Restart capa-controller-manager deployment.
      include_tasks: tasks/restart_capa_controller_manager.yml
      when: selected_action == "8"

    - name: Create rosa-creds-secret.
      include_tasks: tasks/create_rosa_creds_secret.yml
      when: selected_action == "9"

    - name: Get the ROSAControlPlane.
      include_tasks: tasks/get_rosa_control_plane.yml
      when: selected_action == "10"

    - name: Create the ROSA HCP Cluster
      include_tasks: tasks/create_rosa_control_plane.yml
      when: selected_action == "11"

    - name: Delete the ROSA HCP Cluster
      include_tasks: tasks/delete_rosa_control_plane.yml
      when: selected_action == "12"

    - name: Enable CAPI and CAPA
      include_tasks: tasks/enable_capi_capa.yml
      when: selected_action == "2"

    - name: Create ROSA-HCP Cluster
      import_role:
        name: capa-cluster-create-rosa-hcp
      vars:
        ocm_client_id: "{{ OCM_CLIENT_ID }}"
        ocm_client_secret: "{{ OCM_CLIENT_SECRET }}"
      when: selected_action == "2"

