- name: Create ROSA HCP cluster with version selection
  hosts: localhost
  any_errors_fatal: true
  vars_files:
    - vars/vars.yml
    - vars/user_vars.yml
  vars_prompt:
    - name: openshift_version_selection
      prompt: |
        Select OpenShift version:
          1 - 4.18 (Stable - Basic features, recommended for production)
          2 - 4.19 (Enhanced - Advanced features, current release)
          3 - 4.20 (Latest - Premium features, early access)
      default: "2"
      private: no
    - name: cluster_name
      prompt: "Enter cluster name"
      default: "rosa-hcp-versioned"
      private: no
    - name: enable_advanced_features
      prompt: "Enable advanced features for this version? (y/n)"
      default: "n"
      private: no
    - name: apply_immediately
      prompt: "Apply configuration immediately? (y/n)"
      default: "n"
      private: no
  tasks:
    - name: Convert version selection to version string
      set_fact:
        openshift_version: "{{ {'1': '4.18', '2': '4.19', '3': '4.20'}[openshift_version_selection] }}"
        apply_immediately: "{{ apply_immediately.lower() in ['y', 'yes', 'true'] }}"
    
    - set_fact:
        ocp_user:  "{{ OCP_HUB_CLUSTER_USER }}"
        ocp_password:  "{{ OCP_HUB_CLUSTER_PASSWORD }}"
        api_url:  "{{ OCP_HUB_API_URL }}"
        mce_namespace: "{{ MCE_NAMESPACE }}"

    - name: Initialize version management
      include_tasks: tasks/version_management.yml

    - name: Prepare ansible runner host
      include_tasks: tasks/prepare_ansible_runner.yml
      when: not skip_ansible_runner | bool

    - name: Login OCP
      include_tasks: tasks/login_ocp.yml

    - name: Create version-aware ROSA HCP Cluster
      include_tasks: tasks/create_rosa_control_plane_versioned.yml