- name: Create ROSA HCP cluster with AutoNode support
  hosts: localhost
  any_errors_fatal: true
  vars_files:
    - vars/vars.yml
    - vars/user_vars.yml
  tasks:
    - set_fact:
        ocp_user:  "{{ OCP_HUB_CLUSTER_USER }}"
        ocp_password:  "{{ OCP_HUB_CLUSTER_PASSWORD }}"
        api_url:  "{{ OCP_HUB_API_URL }}"
        mce_namespace: "{{ MCE_NAMESPACE }}"

    - name: Prepare ansible runner host
      include_tasks: tasks/prepare_ansible_runner.yml
      when: not skip_ansible_runner | bool

    - name: Login OCP
      include_tasks: tasks/login_ocp.yml

    - name: Validate AutoNode setup (if enabled)
      include_tasks: tasks/validate_autonode_setup.yml
      when: AUTONODE_TESTING_ENABLED | default(false)

    - name: Determine cluster configuration file
      set_fact:
        cluster_config_file: |
          {% if AUTONODE_DEFAULT_MODE | default('disabled') == 'enabled' %}
          rosa-control-plane-autonode-enabled.yaml
          {% else %}
          rosa-control-plane-autonode-disabled.yaml
          {% endif %}

    - name: Display selected configuration
      debug:
        msg: |
          🚀 Creating ROSA HCP cluster with configuration:
          - Config file: {{ cluster_config_file }}
          - AutoNode mode: {{ AUTONODE_DEFAULT_MODE | default('disabled') }}
          {% if AUTONODE_DEFAULT_MODE | default('disabled') == 'enabled' %}
          - Karpenter role: {{ AUTONODE_KARPENTER_ROLE_ARN | default('Not configured') }}
          {% endif %}

    - name: Create the ROSA HCP Cluster with AutoNode
      include_tasks: tasks/create_rosa_control_plane_autonode.yml