version: '3.8'

services:
  backend:
    build:
      context: ./ui/backend
      dockerfile: Dockerfile
    container_name: rosa-automation-backend-prod
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - DEBUG=false
      - LOG_LEVEL=INFO
      - LOG_JSON=true
      - HOST=0.0.0.0
      - PORT=8000
      - CORS_ORIGINS=${CORS_ORIGINS}
      - SECRET_KEY=${SECRET_KEY}
    env_file:
      - .env.prod
    networks:
      - rosa-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./ui/frontend
      dockerfile: Dockerfile.prod
    container_name: rosa-automation-frontend-prod
    ports:
      - "80:80"
    networks:
      - rosa-network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  rosa-network:
    driver: bridge
