---
- name: End-to-End AutoNode Testing for PR #5686
  hosts: localhost
  any_errors_fatal: true
  vars_files:
    - vars/vars.yml
    - vars/user_vars.yml
  vars:
    test_results: []
    autonode_test_scenarios:
      - name: "autonode-enabled"
        description: "Test ROSA HCP cluster with AutoNode/Karpenter enabled"
        autonode_mode: "enabled"
        expected_outcome: "success"
        cluster_name: "rosa-e2e-autonode"
        config_file: "rosa-control-plane-autonode-enabled.yaml"

      - name: "autonode-disabled"
        description: "Test ROSA HCP cluster with AutoNode disabled (baseline)"
        autonode_mode: "disabled"
        expected_outcome: "success"
        cluster_name: "rosa-e2e-traditional"
        config_file: "rosa-control-plane-autonode-disabled.yaml"

  tasks:
    - name: Initialize test environment
      block:
        - name: Set test start time
          set_fact:
            test_start_time: "{{ ansible_date_time.iso8601 }}"

        - name: Create test results directory
          file:
            path: "{{ AUTONODE_TESTING.reports_dir | default('results/autonode-tests') }}"
            state: directory

        - name: Display test plan
          debug:
            msg: |
              🧪 AutoNode End-to-End Test Plan
              ================================

              Test Scenarios: {{ autonode_test_scenarios | length }}
              {% for scenario in autonode_test_scenarios %}
              {{ loop.index }}. {{ scenario.name }}: {{ scenario.description }}
              {% endfor %}

              Environment:
              - AWS Region: {{ AWS_REGION }}
              - CAPI Namespace: {{ capi_namespace }}
              - MCE Namespace: {{ mce_namespace }}

    - name: Prepare test environment
      block:
        - name: Prepare ansible runner host
          include_tasks: tasks/prepare_ansible_runner.yml
          when: not skip_ansible_runner | bool

        - name: Login to OCP
          include_tasks: tasks/login_ocp.yml

        - name: Validate AutoNode prerequisites
          include_tasks: tasks/validate_autonode_setup.yml

    - name: Execute AutoNode test scenarios
      include_tasks: tasks/autonode_test_scenario.yml
      vars:
        current_scenario: "{{ item }}"
        scenario_index: "{{ ansible_loop.index }}"
      loop: "{{ autonode_test_scenarios }}"
      loop_control:
        loop_var: item
        extended: yes

    - name: Generate test report
      include_tasks: tasks/generate_autonode_test_report.yml

    - name: Cleanup test resources
      include_tasks: tasks/cleanup_autonode_test_resources.yml
      when: AUTONODE_TESTING.cleanup_on_success | default(true)