---
- name: "Cleanup ROSARoleConfig for cluster {{ cluster_name }}"
  block:
    - name: Check if ROSARoleConfig exists
      kubernetes.core.k8s_info:
        api_version: infrastructure.cluster.x-k8s.io/v1beta2
        kind: ROSARoleConfig
        name: "{{ cluster_name }}-role-config"
        namespace: "{{ capi_namespace }}"
      register: existing_role_config

    - name: Delete ROSARoleConfig if it exists
      kubernetes.core.k8s:
        api_version: infrastructure.cluster.x-k8s.io/v1beta2
        kind: ROSARoleConfig
        name: "{{ cluster_name }}-role-config"
        namespace: "{{ capi_namespace }}"
        state: absent
        wait: true
        wait_timeout: 600
      when: existing_role_config.resources | length > 0
      register: deletion_result

    - name: Wait for ROSARoleConfig deletion to complete
      kubernetes.core.k8s_info:
        api_version: infrastructure.cluster.x-k8s.io/v1beta2
        kind: ROSARoleConfig
        name: "{{ cluster_name }}-role-config"
        namespace: "{{ capi_namespace }}"
      register: check_deletion
      until: check_deletion.resources | length == 0
      retries: 20
      delay: 30
      when: existing_role_config.resources | length > 0

    - name: Display deletion status
      debug:
        msg: "ROSARoleConfig {{ cluster_name }}-role-config has been successfully deleted"
      when: existing_role_config.resources | length > 0

    - name: Clean up generated role config file
      file:
        path: "{{ output_dir }}/{{ cluster_name }}-rosa-role-config.yaml"
        state: absent
      ignore_errors: true

    - name: Verify AWS roles cleanup (optional manual verification)
      debug:
        msg:
          - "ROSARoleConfig deletion completed."
          - "Note: Verify manually that AWS IAM roles with prefix '{{ cluster_name_prefix | default(cluster_name) }}' have been cleaned up."
          - "Use: rosa list account-roles --prefix {{ cluster_name_prefix | default(cluster_name) }}"
          - "Use: rosa list operator-roles --prefix {{ cluster_name_prefix | default(cluster_name) }}"

  rescue:
    - name: Handle cleanup failure
      debug:
        msg: "Failed to cleanup ROSARoleConfig: {{ ansible_failed_result.msg }}"

    - name: Get ROSARoleConfig status for debugging
      kubernetes.core.k8s_info:
        api_version: infrastructure.cluster.x-k8s.io/v1beta2
        kind: ROSARoleConfig
        name: "{{ cluster_name }}-role-config"
        namespace: "{{ capi_namespace }}"
      register: debug_cleanup_status
      ignore_errors: true

    - name: Display cleanup debug information
      debug:
        var: debug_cleanup_status
      when: debug_cleanup_status is defined

    - name: Continue despite cleanup failure
      debug:
        msg: "Continuing despite ROSARoleConfig cleanup failure - manual cleanup may be required"