- name: Ensure directory for ./results/cap-enable-test
  file: path="./results/cap-enable-test" state=directory

- name: force update of current timestamp
  setup: filter='ansible_date_time'

- name: Create End Timestamp
  set_fact:
    TIMESTAMP_end: "{{ '%Y-%m-%d %H:%M:%S' | strftime(ansible_date_time.epoch) }}"
    results_dir: "./results/cap-enable-test"

- name: Print End Timestamp
  debug:
    msg: "End:   {{ TIMESTAMP_end }}"

- name: Calculate time difference
  set_fact:
    difference: "{{ (TIMESTAMP_end | to_datetime - TIMESTAMP_start | to_datetime).seconds }}"

- name: Print time difference
  debug:
    msg: "End:   {{ difference }}"

- name: Create results.xml from template
  template: src=results.xml.j2 dest={{ results_dir }}/results.xml
  vars:
    polarion_test_id: "RHACM4K-56157"
    component: "CAPI"
    polarion_test_description: "Enable and disable test for capi and capa"
    timestamp: "{{ now() }}"
    execution_time: "{{ difference }}"
    mce_namespace: "multicluster-engine"
  with_items:
    - results.xml

- name: Read results
  shell: cat {{ results_dir }}/results.xml
  register: results

- name: Print results.xml
  debug:
    var: 'results.stdout_lines'
