- name: Login OCP with {{ ocp_user }}
  shell: |
    oc --insecure-skip-tls-verify login -u {{ ocp_user }} -p {{ ocp_password }} -s {{ api_url }}
  changed_when: true

- name: Print OCP login Information
  debug:
    msg: "Logging in with user: {{ ocp_user }} api_url: {{ api_url }}"
