- name: Login OCP with {{ ocp_user }}
  shell: |
    oc --insecure-skip-tls-verify login -u {{ ocp_user }} -p {{ ocp_password }} -s {{ api_url }}
  changed_when: true

- name: Store OCP context name
  shell: oc config current-context
  register: ocp_context_result
  changed_when: false

- name: Set OCP context as fact
  set_fact:
    ocp_context: "{{ ocp_context_result.stdout }}"

- name: Print OCP login Information
  debug:
    msg: "Logging in with user: {{ ocp_user }} api_url: {{ api_url }} context: {{ ocp_context }}"
