- name: Get capa-controller-manager pod name before restart.
  shell: |
    oc get pod -n multicluster-engine -ojson |\
      jq -c '.items[] | select(.metadata.name | contains("capa-controller-manager")) | .metadata.name'
  register: previous_pod_name

- name: Restart the capa-controller-manager deployment.
  shell: |
    oc rollout restart deployment capa-controller-manager -n multicluster-engine

- name: Wait for new capa-controller-manager pod
  shell: |
    oc get pod -n multicluster-engine -ojson |\
      jq -c '.items[] | select(.metadata.name | contains("capa-controller-manager")) | .metadata.name'
  register: current_pod_name
  retries: 12
  delay: 15
  until: previous_pod_name.stdout != current_pod_name.stdout

- name: print output
  debug:
    msg: " pod name before {{ previous_pod_name.stdout }} pod_name_after {{ current_pod_name.stdout }}"
