- name: Set the AWSClusterControllerIdentity
  copy:
    content: |
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
      kind: AWSClusterControllerIdentity
      metadata:
        name: "default"
      spec:
        allowedNamespaces: {}  # matches all namespaces
    dest: "{{ output_dir }}/aws_cluster-controller_identity.yaml"

- name: Apply aws_cluster-controller_identity.yaml
  shell: |
    oc apply -f {{ output_dir }}/aws_cluster-controller_identity.yaml
