---
- name: Update CAPA controller image to 4.20 development version
  block:
    - name: Get current CAPA controller deployment
      kubernetes.core.k8s_info:
        api_version: apps/v1
        kind: Deployment
        name: capa-controller-manager
        namespace: capa-system
      register: current_deployment

    - name: Display current CAPA controller image
      debug:
        msg: "Current CAPA controller image: {{ current_deployment.resources[0].spec.template.spec.containers[0].image }}"
      when: current_deployment.resources | length > 0

    - name: Update CAPA controller deployment with 4.20 image
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: capa-controller-manager
            namespace: capa-system
          spec:
            template:
              spec:
                containers:
                  - name: manager
                    image: "{{ capa_420_image }}:{{ capa_420_tag }}"
        merge_type: strategic-merge-patch
      register: image_update_result

    - name: Wait for CAPA controller deployment to be updated
      kubernetes.core.k8s_info:
        api_version: apps/v1
        kind: Deployment
        name: capa-controller-manager
        namespace: capa-system
        wait: true
        wait_condition:
          type: Progressing
          status: "True"
          reason: NewReplicaSetAvailable
        wait_timeout: 300
      register: deployment_updated

    - name: Wait for CAPA controller pods to be ready with new image
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: capa-system
        label_selectors:
          - control-plane=capa-controller-manager
        wait: true
        wait_condition:
          type: Ready
          status: "True"
        wait_timeout: 300
      register: pods_ready

    - name: Verify new image is running
      kubernetes.core.k8s_info:
        api_version: apps/v1
        kind: Deployment
        name: capa-controller-manager
        namespace: capa-system
      register: updated_deployment

    - name: Display updated CAPA controller image
      debug:
        msg: "Updated CAPA controller image: {{ updated_deployment.resources[0].spec.template.spec.containers[0].image }}"

    - name: Validate image update
      assert:
        that:
          - updated_deployment.resources[0].spec.template.spec.containers[0].image == capa_420_image + ":" + capa_420_tag
        fail_msg: "CAPA controller image was not updated correctly"
        success_msg: "CAPA controller successfully updated to 4.20 development image"

  rescue:
    - name: Handle image update failure
      debug:
        msg: "Failed to update CAPA controller image: {{ ansible_failed_result.msg }}"

    - name: Get CAPA controller logs for debugging
      command: kubectl logs -n capa-system deployment/capa-controller-manager --tail=50
      register: controller_logs
      ignore_errors: true

    - name: Display controller logs for debugging
      debug:
        var: controller_logs.stdout
      when: controller_logs is defined

    - name: Fail the task
      fail:
        msg: "CAPA controller image update failed"