---
- name: "Validate ROSARoleConfig for cluster {{ cluster_name }}"
  block:
    - name: Check ROSARoleConfig status
      kubernetes.core.k8s_info:
        api_version: infrastructure.cluster.x-k8s.io/v1beta2
        kind: ROSARoleConfig
        name: "{{ cluster_name }}-role-config"
        namespace: "{{ capi_namespace }}"
      register: role_config_info

    - name: Display ROSARoleConfig details
      debug:
        var: role_config_info.resources[0]
      when: role_config_info.resources | length > 0

    - name: Validate ROSARoleConfig exists and is ready
      assert:
        that:
          - role_config_info.resources | length > 0
          - role_config_info.resources[0].status is defined
          - role_config_info.resources[0].status.ready is defined
          - role_config_info.resources[0].status.ready == true
        fail_msg: "ROSARoleConfig is not ready or doesn't exist"
        success_msg: "ROSARoleConfig validation passed"

    - name: Extract role ARNs from ROSARoleConfig status
      set_fact:
        account_role_arns: "{{ role_config_info.resources[0].status.accountRoleARNs | default({}) }}"
        operator_role_arns: "{{ role_config_info.resources[0].status.operatorRoleARNs | default({}) }}"
        oidc_provider_arn: "{{ role_config_info.resources[0].status.oidcProviderARN | default('') }}"
      when: role_config_info.resources | length > 0

    - name: Display created AWS role ARNs
      debug:
        msg:
          - "Account Roles: {{ account_role_arns }}"
          - "Operator Roles: {{ operator_role_arns }}"
          - "OIDC Provider: {{ oidc_provider_arn }}"

    - name: Validate required account roles were created
      assert:
        that:
          - account_role_arns.installer is defined
          - account_role_arns.support is defined
          - account_role_arns.worker is defined
        fail_msg: "Required account roles (installer, support, worker) were not created"
        success_msg: "All required account roles were created"
      when: account_role_arns is defined

    - name: Validate required operator roles were created
      assert:
        that:
          - operator_role_arns.ingress is defined
          - operator_role_arns.imageRegistry is defined
          - operator_role_arns.storage is defined
          - operator_role_arns.network is defined
        fail_msg: "Required operator roles were not created"
        success_msg: "All required operator roles were created"
      when: operator_role_arns is defined

    - name: Validate OIDC provider was created
      assert:
        that:
          - oidc_provider_arn != ""
          - oidc_provider_arn is match("arn:aws:iam::")
        fail_msg: "OIDC provider was not created or invalid ARN"
        success_msg: "OIDC provider was created successfully"
      when: oidc_provider_arn is defined

  rescue:
    - name: Handle validation failure
      debug:
        msg: "ROSARoleConfig validation failed: {{ ansible_failed_result.msg }}"

    - name: Get ROSARoleConfig for debugging
      kubernetes.core.k8s_info:
        api_version: infrastructure.cluster.x-k8s.io/v1beta2
        kind: ROSARoleConfig
        name: "{{ cluster_name }}-role-config"
        namespace: "{{ capi_namespace }}"
      register: debug_role_config

    - name: Display ROSARoleConfig for debugging
      debug:
        var: debug_role_config

    - name: Fail the validation
      fail:
        msg: "ROSARoleConfig validation failed"