apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: ROSARoleConfig
metadata:
  name: acm21162-test-role-config
  namespace: ns-rosa-hcp
spec:
  identityRef:
    kind: AWSClusterControllerIdentity
    name: default
  credentialsSecretRef:
    name: rosa-creds-secret
  accountRoleConfig:
    prefix: "acm21162"
    version: "4.20"
  operatorRoleConfig:
    prefix: "acm21162"