version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../:/app/automation-capi:ro  # Mount automation scripts
      - ${HOME}/.kube:/root/.kube:ro  # Mount kubeconfig for kubectl/kind access
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket for Kind
    environment:
      - PYTHONPATH=/app
      - AUTOMATION_PATH=/app/automation-capi
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped

  # Optional: Add Redis for job queue and caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data: