name: Pull Request Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-metadata:
    name: PR Metadata Check
    runs-on: ubuntu-latest

    steps:
      - name: Check PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            test
            chore
          requireScope: false

  pr-size:
    name: PR Size Check
    runs-on: ubuntu-latest

    steps:
      - name: Check PR size
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const additions = pr.additions;
            const deletions = pr.deletions;
            const changes = additions + deletions;

            console.log(`PR has ${changes} total changes (${additions} additions, ${deletions} deletions)`);

            if (changes > 1000) {
              core.setFailed('PR is too large! Consider breaking it into smaller PRs. Total changes: ' + changes);
            } else if (changes > 500) {
              core.warning('PR is quite large. Consider breaking it into smaller PRs if possible. Total changes: ' + changes);
            }

  pr-labels:
    name: PR Label Check
    runs-on: ubuntu-latest

    steps:
      - name: Check for labels
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const labels = pr.labels.map(label => label.name);

            if (labels.length === 0) {
              core.warning('PR has no labels. Please add appropriate labels.');
            }

  test-coverage:
    name: Test Coverage Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install backend dependencies
        run: |
          cd ui/backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check backend coverage
        run: |
          cd ui/backend
          pytest --cov=. --cov-report=term --cov-fail-under=0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: |
          cd ui/frontend
          npm ci

      - name: Check frontend coverage
        run: |
          cd ui/frontend
          npm test -- --coverage --watchAll=false --coverageThreshold='{"global":{"lines":0}}'

  changed-files:
    name: Check Changed Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            ui/backend/**
            ui/frontend/**

      - name: List changed files
        run: |
          echo "Changed backend files: ${{ steps.changed-files.outputs.all_changed_files }}"

      - name: Comment on PR
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const changedFiles = '${{ steps.changed-files.outputs.all_changed_files }}'.split(' ');
            const backendFiles = changedFiles.filter(f => f.startsWith('ui/backend/'));
            const frontendFiles = changedFiles.filter(f => f.startsWith('ui/frontend/'));

            let comment = '### Changed Files Summary\n\n';
            if (backendFiles.length > 0) {
              comment += `**Backend files changed:** ${backendFiles.length}\n`;
            }
            if (frontendFiles.length > 0) {
              comment += `**Frontend files changed:** ${frontendFiles.length}\n`;
            }

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
