# Create Azure credentials secret for CAPZ
- name: Create Azure Service Principal secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ azure_creds_secret }}"
        namespace: "{{ provider_namespace }}"
      type: Opaque
      data:
        clientId: "{{ lookup('env', 'AZURE_CLIENT_ID') | b64encode }}"
        clientSecret: "{{ lookup('env', 'AZURE_CLIENT_SECRET') | b64encode }}"
        subscriptionId: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') | b64encode }}"
        tenantId: "{{ lookup('env', 'AZURE_TENANT_ID') | b64encode }}"

- name: Create CAPZ manager bootstrap credentials
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: capz-manager-bootstrap-credentials
        namespace: "{{ provider_namespace }}"
      type: Opaque
      data:
        clientId: "{{ lookup('env', 'AZURE_CLIENT_ID') | b64encode }}"
        clientSecret: "{{ lookup('env', 'AZURE_CLIENT_SECRET') | b64encode }}"
        subscriptionId: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') | b64encode }}"
        tenantId: "{{ lookup('env', 'AZURE_TENANT_ID') | b64encode }}"