# Validate Azure credentials are available
- name: Check required Azure environment variables
  assert:
    that:
      - lookup('env', item) | length > 0
    fail_msg: "Required Azure credential '{{ item }}' is not set"
  loop: "{{ azure_credentials }}"
  when: azure_credentials is defined

- name: Validate Azure CLI availability (optional)
  shell: which az
  register: az_cli_check
  failed_when: false
  changed_when: false

- name: Display Azure CLI status
  debug:
    msg: "Azure CLI {{ 'available' if az_cli_check.rc == 0 else 'not available' }}"