# Wait for AKS control plane to be ready
- name: Wait for AKS control plane to be ready
  kubernetes.core.k8s_info:
    api_version: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureManagedControlPlane
    name: "{{ cluster_name }}-control-plane"
    namespace: "{{ capi_namespace }}"
    wait: true
    wait_condition:
      type: Ready
      status: "True"
    wait_timeout: "{{ cluster_ready_timeout | default('20m') }}"
  register: aks_control_plane_status

- name: Display AKS control plane ready status
  debug:
    msg: "AKS control plane is ready: {{ aks_control_plane_status.resources[0].status.ready | default('Unknown') }}"